### ISSUE TITLE
Multi-Provider ACM

### ISSUE THREAD

**Issue by smilite** [terraform-aws-modules/terraform-aws-acm#25]
Hello together,

I use the acm module for my infrastructure in order to create and validate domain/certificates. But:
If I have a loadbalancer in a separated organization (and route53 zone is in root account), I can not run my project with the organization role because the acm module has no support for multiple providers. 

My question: Is it possible to add multi-provider support?

---
EDIT: I just tested it with my code: If I run terraform with organizational unit credential, the route53 record must be validated through the account that owns the route53 zone.
Certificate (and its validation) must be made in OU subaccount so they can be reused for loadbalancers.

**Comment by antonbabenko** [comment]
Hi @smilite !

This sounds like a legit feature request to consider.

Currently, there is no way to provide different providers to a module (one to create ACM certificate and validate, and another - to create Route53 records) due to a lack of Terraform dynamic configurations in `providers` meta-argument.

I think you should be able to do this in two steps:
1. Create ACM certificate and don't validate it (`validate_certificate = false`) using one AWS provider.
2. Create validation records using another instance of AWS provider without using this module. Once records are created you can validate it using `aws_acm_certificate_validation` resource. You can get examples of the required code from this module.

I don't think this module will implement such functionality in the near future, so I am going to close this issue.
